name: Build and push image to DockerHub

on:
  push:
    branches: ["main"]

jobs:
  build-image-and-push-to-registry:
    runs-on: ubuntu-latest
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Retrieve repository content
        uses: actions/checkout@v2
      - name: Build Docker image and push to DockerHub
        uses: docker/build-push-action@v3
        with:
          context: ./
          file: ./Dockerfile
          push: true
          tags: adesojikola/gh-actions-ci-cd-pipeline:1.0.${{github.run_number}}
